### PR TITLE
Bump CAPI to v1.5.0

### LINKED ISSUE #3680: CAPI v1.5.0-beta.0 has been released and is ready for testing
CAPI `v1.5.0-beta.0` has been released and is ready for testing.
Looking forward to your feedback before CAPI 1.5.0 release, the 25th July 2023!

## For quick reference

- [CAPI v1.5.0-beta.0 release notes](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.5.0-beta.0)
- [Shortcut to CAPI git issues](https://github.com/kubernetes-sigs/cluster-api/issues)

## Following are the planned dates for the upcoming releases

|Release|Expected Date|
|-----|-----|
|v1.5.0-beta.x | Tuesday 5th July 2023|
|release-1.5 branch created (Begin [Code Freeze])|Tuesday 11th July 2023|
|v1.5.0-rc.0 released|Tuesday 11th July 2023|
| release-1.5 jobs created | Tuesday 11th July 2023 |
| v1.5.0-rc.x released | Tuesday 18th July 2023 |
| v1.5.0 released | Tuesday 25th July 2023 |

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates CAPI to [v1.5.0](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.5.0) and all that entails.

**Which issue(s) this PR fixes**:

Fixes #3680
Closes #3751
Closes #3773

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Bump CAPI to v1.5.0
```

### CODE REVIEW

**Comment by mboersma** [comment]
I have a handle on fixing the remaining errors related to controller-runtime, except for this one:

```go
# github.com/Azure/azure-service-operator/v2/api/resources/v1api20200601
../../../pkg/mod/github.com/!azure/azure-service-operator/v2@v2.1.0/api/resources/v1api20200601/resource_group_types_gen.go:178:29: cannot use &ResourceGroup{} (value of type *ResourceGroup) as admission.Validator value in variable declaration: *ResourceGroup does not implement admission.Validator (wrong type for method ValidateCreate)
		have ValidateCreate() error
		want ValidateCreate() (admission.Warnings, error)
make: *** [Makefile:198: manager] Error 1
```

@nojnhuh does this imply we need a new release of ASO?

**Comment by nojnhuh** [comment]
A temporary alternative to waiting for an ASO release would be ripping out all of our ASO resource group stuff.

**Comment by mboersma** [comment]
I opened a request for controller-runtime v0.15.0 support at Azure/azure-service-operator#3137. Hopefully they're ok with upgrading–it is a breaking change.

**Comment by Jont828** [comment]
@mboersma Yeah that's unfortunate that the versions of controller runtime don't line up. Is there anything we can do for that besides wait for them to release a new version after upgrading to v0.15.0?

**Review by Jont828 — COMMENTED** [review]
LGTM pending the ASO issue

**Comment by mboersma** [comment]
> Is there anything we can do for that besides wait...?

We could back out the current ASO implementation for resource groups if need be, but that wouldn't really change anything, just buy some more time.

**Comment by Jont828** [comment]
Sounds good. Do you have an idea of when we want to get this PR in? We would need to get this in order to merge #3736 as it requires bumping to v1.5 as well.

**Comment by mboersma** [comment]
> when we want to get this PR in?

As soon as we can after the CAPI release, as always (planned for [July 25](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/releases/release-1.5.md#timeline)), but we will also need to get a new ASO release and we don't control that timeline. The good news is that team pounced on our request and already have a PR in review that upgrades controller-runtime to match CAPI 1.5, so hopefully an ASO release isn't far away.

**Comment by nojnhuh** [comment]
@mboersma Here are the changes to include ASO v2.2.0 which includes controller-runtime 0.15: https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/28b88459

It looks like ASO's CRD manifest and docker image for the new release aren't out yet, but I've asked about that in Slack and did a quick smoke test with locally-built versions and I expect everything to work once things are published.

**Comment by nojnhuh** [comment]
> It looks like ASO's CRD manifest and docker image for the new release aren't out yet, but I've asked about that in Slack and did a quick smoke test with locally-built versions and I expect everything to work once things are published.

ASO release kinks appear to have been worked out.

**Comment by mboersma** [comment]
> Unable to run conformance tests: failed to attach to container "": http: invalid Host header

This is https://github.com/golang/go/issues/61431 because CAPI v1.5.0 was built with the Go compiler that has this regression. They're discussing a fix in Cluster API; we may have to wait for another -rc release.

**Comment by mboersma** [comment]
It's really unfortunate that we had to move Docker ahead, because there's an incompatibility with Helm with no obvious workaround. In CAPI they [removed the dependency](https://github.com/kubernetes-sigs/cluster-api/pull/9038/files#r1270754590) on Helm, but CAPZ has much deeper integration and I don't think that's reasonable to do.

**Comment by mboersma** [comment]
/hold

I rebased this off #3756, which will need to merge first.

**Comment by mboersma** [comment]
/retitle Bump CAPI to v1.5.0

Just waiting for other PRs to merge so this can be rebased, but it appears to be working.

File: main.go [hunk 1]
```diff
@@ -277,11 +270,24 @@ func main() {
 		RenewDeadline:              &leaderElectionRenewDeadline,
 		RetryPeriod:                &leaderElectionRetryPeriod,
 		LeaderElectionResourceLock: resourcelock.LeasesResourceLock,
-		SyncPeriod:                 &syncPeriod,
-		Namespace:                  watchNamespace,
 		HealthProbeBindAddress:     healthAddr,
-		Port:                       webhookPort,
-		EventBroadcaster:           broadcaster,
+		PprofBindAddress:           profilerAddress,
```
Comment (mboersma) [inline main.go:274]: These changes in main.go are following similar changes CAPI made.

File: test/e2e/azure_logcollector.go [hunk 2]
```diff
@@ -125,6 +125,11 @@ func (k AzureLogCollector) CollectMachinePoolLog(ctx context.Context, management
 	return kinderrors.NewAggregate(errs)
 }
 
+// CollectInfrastructureLogs collects log from the infrastructure.
+func (k AzureLogCollector) CollectInfrastructureLogs(ctx context.Context, managementClusterClient client.Client, c *clusterv1.Cluster, outputPath string) error {
```
Comment (mboersma) [inline test/e2e/azure_logcollector.go:129]: This is a dummy implementation of a new func necessary to satisfy the log collector interface.

File: test/e2e/common.go [hunk 3]
```diff
@@ -284,13 +283,7 @@ func EnsureControlPlaneInitialized(ctx context.Context, input clusterctl.ApplyCl
 		InstallCNI(ctx, input, cluster.Spec.ClusterNetwork.Pods.CIDRBlocks, hasWindows)
 	}
 	controlPlane := discoveryAndWaitForControlPlaneInitialized(ctx, input, result)
-	v, err := semver.ParseTolerant(input.ConfigCluster.KubernetesVersion)
```
Comment (mboersma) [inline test/e2e/common.go:287]: With the new watcher interface, we use new input and result structs that don't have any way to get Kubernetes version. Can we stop worrying about this pre-1.23 rule?

File: test/e2e/cloud-provider-azure.go [hunk 4]
```diff
@@ -60,11 +60,11 @@ func InstallCalicoAndCloudProviderAzureHelmChart(ctx context.Context, input clus
 		options.StringValues = append(options.StringValues, fmt.Sprintf("cloudNodeManager.imageTag=%s", os.Getenv("IMAGE_TAG_CNM")))
 	}
 
-	if input.ConfigCluster.Flavor == "flatcar" {
+	if strings.Contains(input.ClusterName, "flatcar") {
```
Comment (mboersma) [inline test/e2e/cloud-provider-azure.go:63]: The new e2e watcher interface uses a different input struct that doesn't have `Flavor`, so the only other way I could think of to detect Flatcar was to look at the cluster name. This is just for e2e, so that will probably work, but feels fragile.

File: test/e2e/azure_logcollector.go (hunk 2 above)
Comment (Jont828) [reply test/e2e/azure_logcollector.go:129]: Just to clarify, does that mean there are logs being thrown out here? Or would it just be duplicates of logs we're already collecting our own way?

File: test/e2e/cloud-provider-azure.go (hunk 4 above)
Comment (Jont828) [reply test/e2e/cloud-provider-azure.go:63]: That's pretty unfortunate when they remove stuff you need... Maybe we can just add a comment for now documenting what you just described.

Comment (CecileRobertMichon) [reply test/e2e/cloud-provider-azure.go:63]: Uh was that intentional or is it possible it was an accidental omission?

Comment (mboersma) [reply test/e2e/cloud-provider-azure.go:63]: It was part of a large test refactoring in kubernetes-sigs/cluster-api#8833 that changed the `Waiter` interface apparently with the assumption it was not being used outside CAPI:

https://github.com/kubernetes-sigs/cluster-api/pull/8833/files#diff-7084fa27f2b10b8d2472295c14187d21ea186aae39efa12e051f340562a4cca4R223

File: api/v1beta1/azuremanagedmachinepool_webhook_test.go [hunk 5]
```diff
@@ -1220,6 +1221,7 @@ func TestAzureManagedMachinePool_validateLastSystemNodePool(t *testing.T) {
 					Name:              systemMachinePool.GetLabels()[clusterv1.ClusterNameLabel],
 					Namespace:         systemMachinePool.Namespace,
 					DeletionTimestamp: &deletionTime,
+					Finalizers:        finalizers,
```
Comment (willie-yao) [inline api/v1beta1/azuremanagedmachinepool_webhook_test.go:1224]: Why are these Finalizers required? I don't see it being used in other tests that are refactored.

File: azure/scope/managedcontrolplane.go [hunk 6]
```diff
@@ -613,6 +613,7 @@ func (s *ManagedControlPlaneScope) MakeEmptyKubeConfigSecret() corev1.Secret {
 			OwnerReferences: []metav1.OwnerReference{
 				*metav1.NewControllerRef(s.ControlPlane, infrav1.GroupVersion.WithKind("AzureManagedControlPlane")),
 			},
+			Labels: map[string]string{clusterv1.ClusterNameLabel: s.Cluster.Name},
```
Comment (willie-yao) [inline azure/scope/managedcontrolplane.go:616]: I might just be misunderstanding but is this related to the bumping CAPI to v1.5?

File: controllers/azuremanagedcontrolplane_controller.go [hunk 7]
```diff
@@ -311,7 +311,7 @@ func (amcpr *AzureManagedControlPlaneReconciler) reconcileDelete(ctx context.Con
 
 // ClusterToAzureManagedControlPlane is a handler.ToRequestsFunc to be used to enqueue requests for
 // reconciliation for AzureManagedControlPlane based on updates to a Cluster.
-func (amcpr *AzureManagedControlPlaneReconciler) ClusterToAzureManagedControlPlane(o client.Object) []ctrl.Request {
+func (amcpr *AzureManagedControlPlaneReconciler) ClusterToAzureManagedControlPlane(ctx context.Context, o client.Object) []ctrl.Request {
```
Comment (willie-yao) [inline controllers/azuremanagedcontrolplane_controller.go:314]: Is this ctx being used anywhere?

File: test/e2e/azure_logcollector.go (hunk 2 above)
Comment (willie-yao) [reply test/e2e/azure_logcollector.go:129]: nit: I think it could help to specify that this is a no-op to satisfy the interface as a comment

File: controllers/azurejson_machine_controller.go [hunk 8]
```diff
@@ -82,7 +82,7 @@ func (r *AzureJSONMachineReconciler) SetupWithManager(ctx context.Context, mgr c
 	// Add a watch on Clusters to requeue when the infraRef is set. This is needed because the infraRef is not initially
 	// set in Clusters created from a ClusterClass.
 	if err := c.Watch(
-		&source.Kind{Type: &clusterv1.Cluster{}},
+		source.Kind(mgr.GetCache(), &clusterv1.Cluster{}),
```
Comment (sonasingh46) [inline controllers/azurejson_machine_controller.go:85]: Is this change due to capi bump?

Comment (sonasingh46) [reply controllers/azurejson_machine_controller.go:85]: Never mind -- this is coming from controller runtime upgrade.

File: azure/scope/managedcontrolplane.go (hunk 6 above)
Comment (sonasingh46) [reply azure/scope/managedcontrolplane.go:616]: Copying myself. I have the same question.

File: exp/controllers/azuremachinepoolmachine_controller_test.go [hunk 9]
```diff
@@ -172,8 +172,9 @@ func getAReadyMachinePoolMachineCluster() (*clusterv1.Cluster, *infrav1.AzureClu
 
 	ampm := &infrav1exp.AzureMachinePoolMachine{
 		ObjectMeta: metav1.ObjectMeta{
-			Name:      "ampm1",
-			Namespace: "default",
+			Name:       "ampm1",
+			Namespace:  "default",
+			Finalizers: []string{"test"},
```
Comment (sonasingh46) [inline exp/controllers/azuremachinepoolmachine_controller_test.go:177]: What was the purpose of adding the finalizer here?

File: test/e2e/common.go (hunk 3 above)
Comment (sonasingh46) [reply test/e2e/common.go:286]: Yes, we can stop worrying about the pre-1.23 rules. This was mainly introduced sometime back to test the OOT transition of csi and cloud-provider-azure. 

I am not sure why "not being able to fetch k8s version" is kind enforced now. But we can worry about this when we need it.

**Comment by sonasingh46** [comment]
A minor nit comment. Everything looks good to me. This was a big one. Thanks @mboersma 

/lgtm

**Comment by sonasingh46** [comment]
A rebase should fix the failures.

File: api/v1beta1/azuremanagedmachinepool_webhook_test.go (hunk 5 above)
Comment (mboersma) [reply api/v1beta1/azuremanagedmachinepool_webhook_test.go:1224]: Good question. This was hard to track down, but some unit tests started erroring with this change, and it boiled down to this (from the controller-runtime v0.15.0 [release notes](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0)):
> Update fake client deletionTimestamp behavior (https://github.com/kubernetes-sigs/controller-runtime/pull/2316)
>  - The fake client will panic if initialized with an object that has a DeletionTimestamp and no finalizer

File: exp/controllers/azuremachinepoolmachine_controller_test.go (hunk 9 above)
Comment (mboersma) [reply exp/controllers/azuremachinepoolmachine_controller_test.go:177]: Good question. I answered [above](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3707#discussion_r1289120353), but basically some tests using CAPI's fake client will now error without finalizers.

File: azure/scope/managedcontrolplane.go (hunk 6 above)
Comment (mboersma) [reply azure/scope/managedcontrolplane.go:616]: Good catch! This does seem random, but deep in the CAPI v1.5.0 [migration guide](https://cluster-api.sigs.k8s.io/developer/providers/migrations/v1.4-to-v1.5#other) there is this comment:
> The generated kubeconfig by the Control Plane providers must be labelled with the key-value pair cluster.x-k8s.io/cluster-name=${CLUSTER_NAME}. This is required for the CAPI managers caches to store and retrieve them for the required operations.

File: controllers/azuremanagedcontrolplane_controller.go (hunk 7 above)
Comment (mboersma) [reply controllers/azuremanagedcontrolplane_controller.go:314]: It is not, but it's now required as part of the changed signature expected by `handler.EnqueueRequestsFromMapFunc()` (the indirect way this function gets called, on line 101 of the same file).

Comment (mboersma) [reply controllers/azuremanagedcontrolplane_controller.go:314]: I can change the variable name to `_` (underscore) to indicate it's unused.

File: test/e2e/azure_logcollector.go (hunk 2 above)
Comment (mboersma) [reply test/e2e/azure_logcollector.go:130]: Done.

File: test/e2e/e2e_suite_test.go [hunk 10]
```diff
@@ -51,6 +53,7 @@ func init() {
 }
 
 func TestE2E(t *testing.T) {
+	ctrl.SetLogger(klog.Background())
```
Comment (mboersma) [inline test/e2e/e2e_suite_test.go:56]: This is needed because of the last statement in the CAPI v1.5.0 [release notes](https://cluster-api.sigs.k8s.io/developer/providers/migrations/v1.4-to-v1.5#notes-about-the-controller-runtime-bump):

> Ensure that the e2e test suite is setting a logger (e.g. via `ctrl.SetLogger(klog.Background())` in `TestE2E`. Otherwise logs are not visible and controller-runtime will print a warning.

File: exp/controllers/helpers_test.go [hunk 11]
```diff
@@ -60,7 +60,7 @@ func TestAzureClusterToAzureMachinePoolsMapper(t *testing.T) {
 	mapper, err := AzureClusterToAzureMachinePoolsMapper(context.Background(), fakeClient, scheme, logr.New(sink))
 	g.Expect(err).NotTo(HaveOccurred())
 
-	requests := mapper(&infrav1.AzureCluster{
+	requests := mapper(context.TODO(), &infrav1.AzureCluster{
```
Comment (Jont828) [inline exp/controllers/helpers_test.go:63]: Should we use `context.Background()` instead?

**Review by Jont828 — COMMENTED** [review]
LGTM pending tests

File: exp/controllers/helpers_test.go (hunk 11 above)
Comment (mboersma) [reply exp/controllers/helpers_test.go:63]: Yes, I think you're right: `context.TODO()` is kind of like "I don't know what context to use here," but `context.Background()` is probably more appropriate in tests.

Comment (mboersma) [reply exp/controllers/helpers_test.go]: Done.

**Comment by mboersma** [comment]
This failure looks real, presumably as a result of this PR:

```go
  [38;5;9m[FAILED] Timed out after 1200.000s.
  The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_securitygroups.go:127 with:
  Expected
      <[]string | len:1, cap:1>: [
          "test-security-rule-2",
      ]
  to contain element matching
      <string>: test-security-rule[0m
```

I'll investigate as soon as I can.

File: test/e2e/cloud-provider-azure.go (hunk 4 above)
Comment (CecileRobertMichon) [reply test/e2e/cloud-provider-azure.go:63]: https://github.com/kubernetes-sigs/cluster-api/pull/9166

File: test/e2e/aks.go [hunk 12]
```diff
@@ -42,7 +42,7 @@ type DiscoverAndWaitForAKSControlPlaneInput struct {
 
 // WaitForAKSControlPlaneInitialized waits for the Azure managed control plane to be initialized.
 // This will be invoked by cluster api e2e framework.
-func WaitForAKSControlPlaneInitialized(ctx context.Context, input clusterctl.ApplyClusterTemplateAndWaitInput, result *clusterctl.ApplyClusterTemplateAndWaitResult) {
+func WaitForAKSControlPlaneInitialized(ctx context.Context, input clusterctl.ApplyCustomClusterTemplateAndWaitInput, result *clusterctl.ApplyCustomClusterTemplateAndWaitResult) {
```
Comment (sbueringer) [inline test/e2e/aks.go:45]: Should this still be ApplyClusterTemplateAndWaitInput?

File: test/e2e/cloud-provider-azure.go (hunk 4 above)
Comment (sbueringer) [reply test/e2e/cloud-provider-azure.go:63]: Q: I don't have the full overview over this could, but could you still use ApplyClusterTemplateAndWaitInput in this func? (I don't see the directly correlation to the Waiter interface, but there is probably an indirect one?)

**Comment by Jont828** [comment]
@mboersma Do you need any help moving this forward?

File: test/e2e/cloud-provider-azure.go (hunk 4 above)
Comment (sbueringer) [reply test/e2e/cloud-provider-azure.go:63]: Okay found it. Propagates down from EnsureControlPlaneInitialized

File: test/e2e/aks.go (hunk 12 above)
Comment (sbueringer) [reply test/e2e/aks.go:45]: Feel free to resolve this one

**Comment by mboersma** [comment]
@Jont828 AFAICT it's ready to go, but we've had several flakes in the main e2e test, including the one I noted above. That test hasn't been that reliable, and the flakes seem to be similar to ones on other PRs.

My only concern is that perhaps v1.5.0 is introducing some further instability there, but it's really hard to discern. I haven't been able to reproduce any of these failures, nor track down any specifics through the logs. They don't seem to be related to this PR, but I can't say so for sure.

**Comment by Jont828** [comment]
Sounds good, I'm comfortable moving this forward if we're seeing similar flakes in other PRs.

**Comment by mboersma** [comment]
Rebased due to a collision in test code from #3826.

**Comment by CecileRobertMichon** [comment]
I looked at the e2e test history and I don't see a pattern in the failures

**Comment by mboersma** [comment]
Rebased again due to collision in go.sum with #3827.

File: test/e2e/retry.go [hunk 13]
```diff
@@ -36,7 +37,7 @@ const (
 // retryWithTimeout retries a function that returns an error until a timeout is reached
 func retryWithTimeout(interval, timeout time.Duration, fn func() error) error {
 	var pollError error
-	err := wait.PollImmediate(interval, timeout, func() (bool, error) {
+	err := wait.PollUntilContextTimeout(context.TODO(), interval, timeout, true, func(context.Context) (bool, error) {
```
Comment (CecileRobertMichon) [inline test/e2e/retry.go:40]: is there a reason you used `PollUntilContextTimeout` instead of `PollWithContextTimeout` here? I see 

> // Deprecated: This method does not return errors from context, use PollWithContextTimeout.
// Note that the new method will no longer return ErrWaitTimeout and instead return errors
// defined by the context package. Will be removed in a future release.

in the wait package

Comment (mboersma) [reply test/e2e/retry.go:40]: AFAICT that's actually a typo, only `PollUntilContextTimeout` seems to exist: https://pkg.go.dev/k8s.io/apimachinery@v0.27.2/pkg/util/wait#PollUntilContextCancel

Comment (CecileRobertMichon) [reply test/e2e/retry.go:40]: talked offline `PollWithContextTimeout` doesn't exist, that code comment is likely a typo

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve
/hold

feel free to remove hold when optional tests have passed

**Comment by Jont828** [comment]
We made it!
